updating sync_forks

diff --git a/.github/workflows/sync_forks.yml b/.github/workflows/sync_forks.yml
--- a/.github/workflows/sync_forks.yml
+++ b/.github/workflows/sync_forks.yml
@@ -29,7 +29,7 @@ jobs:
           REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/meefs/repos?type=forks&per_page=100&page=1")
 
           # Loop through each repository and sync
-          echo "$REPOS" | jq -r '.[] | .full_name + " " + .clone_url' | while IFS=" " read -r REPO_FULL_NAME REPO_CLONE_URL; do
+          echo "$REPOS" | jq -r '.[] | .full_name + " " + .clone_url + " " + .parent.clone_url' | while IFS=" " read -r REPO_FULL_NAME REPO_CLONE_URL UPSTREAM_CLONE_URL; do
             echo "Processing $REPO_FULL_NAME"
             
             # Extract repository name
@@ -39,14 +39,23 @@ jobs:
             if git clone "$REPO_CLONE_URL" "$REPO_NAME"; then
               cd "$REPO_NAME"
               
+              # Add upstream repository
+              git remote add upstream "$UPSTREAM_CLONE_URL"
+
+              # Fetch updates from the upstream repository
+              git fetch upstream
+
               # Fetch repository details to get the default branch name
               REPO_DETAILS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO_FULL_NAME")
               DEFAULT_BRANCH=$(echo "$REPO_DETAILS" | jq -r '.default_branch')
 
-              # Check if the default branch exists
+              # Check if the default branch exists and merge changes from upstream
               if [ -n "$DEFAULT_BRANCH" ]; then
-                # Pull updates from the default branch of the original repository
-                git pull origin "$DEFAULT_BRANCH" || echo "Failed to pull from $DEFAULT_BRANCH"
+                git checkout "$DEFAULT_BRANCH"
+                git merge upstream/"$DEFAULT_BRANCH" --allow-unrelated-histories -m "Merged by GitHub Actions" || echo "Failed to merge from upstream/$DEFAULT_BRANCH"
+                
+                # Push updates back to the fork on GitHub
+                git push origin "$DEFAULT_BRANCH" || echo "Failed to push updates to $REPO_FULL_NAME"
               else
                 echo "Default branch not found for $REPO_FULL_NAME"
               fi
